User.create(first_name: 'Bruno', last_name: 'Parma', username: 'brunoparma')
User.create(first_name: 'Larry', last_name: 'Page', username: 'larrypage')
User.create(first_name: 'Elon', last_name: 'Musk', username: 'elonmusk')
User.create(first_name: 'Jeff', last_name: 'Bezos', username: 'jeffbezos')
User.create(first_name: 'Tim', last_name: 'Cook', username: 'timcook')
